export const mockUsers = [
  {
    id: "1",
    name: "Engr. Amina Bello",
    email: "amina.bello@son.gov.ng",
    avatar: "",
    role: "Director of Standards",
    department: "Standards and Quality Assurance",
    status: "Active" as const,
    joinedDate: "10 Jan 2015, 8:45 am",
    phone: "+234 801 234 5678",
    address: "SON Headquarters, Abuja, Nigeria",
    bio: "Oversees the development and enforcement of national product standards across all sectors.",
  },
  {
    id: "2",
    name: "Mr. Chukwuemeka Obi",
    email: "chukwuemeka.obi@son.gov.ng",
    avatar: "",
    role: "Chief Inspector",
    department: "Compliance and Inspection",
    status: "Active" as const,
    joinedDate: "22 Jul 2018, 11:15 am",
    phone: "+234 802 345 6789",
    address: "SON Regional Office, Enugu, Nigeria",
    bio: "Responsible for coordinating nationwide product inspections and compliance reporting.",
  },
  {
    id: "3",
    name: "Mrs. Fatima Lawal",
    email: "fatima.lawal@son.gov.ng",
    avatar: "",
    role: "Procurement Officer",
    department: "Procurement and Logistics",
    status: "Active" as const,
    joinedDate: "05 May 2020, 10:30 am",
    phone: "+234 803 456 7890",
    address: "SON Zonal Office, Kaduna, Nigeria",
    bio: "Manages supplier evaluation, purchase orders, and procurement documentation within SON.",
  },
  {
    id: "4",
    name: "Mr. Ahmed Yusuf",
    email: "ahmed.yusuf@son.gov.ng",
    avatar: "",
    role: "Finance Controller",
    department: "Finance and Accounts",
    status: "Active" as const,
    joinedDate: "14 Feb 2019, 9:20 am",
    phone: "+234 804 567 8901",
    address: "SON Headquarters, Abuja, Nigeria",
    bio: "Supervises budget planning, auditing, and financial transactions for SON projects and departments.",
  },
  {
    id: "5",
    name: "Dr. Grace Okafor",
    email: "grace.okafor@son.gov.ng",
    avatar: "",
    role: "Research Analyst",
    department: "Science and Research",
    status: "Inactive" as const,
    joinedDate: "09 Oct 2017, 12:10 pm",
    phone: "+234 805 678 9012",
    address: "SON Research Unit, Ibadan, Nigeria",
    bio: "Conducts scientific studies to support standardization and product testing policies.",
  },
  {
    id: "6",
    name: "Mr. Daniel Ekene",
    email: "daniel.ekene@son.gov.ng",
    avatar: "",
    role: "ICT Administrator",
    department: "ICT",
    status: "Active" as const,
    joinedDate: "03 Dec 2022, 12:05 pm",
    phone: "+234 806 789 0123",
    address: "SON ICT Hub, Enugu, Nigeria",
    bio: "Manages SON’s enterprise systems, ERP integration, and IT security infrastructure.",
  },
  {
    id: "7",
    name: "Mrs. Juliet Nwosu",
    email: "juliet.nwosu@son.gov.ng",
    avatar: "",
    role: "Public Relations Officer",
    department: "Corporate Affairs",
    status: "Active" as const,
    joinedDate: "18 Sep 2019, 10:00 am",
    phone: "+234 807 890 1234",
    address: "SON Corporate Affairs Office, Lagos, Nigeria",
    bio: "Handles communication strategies and public awareness campaigns for SON operations.",
  },
  {
    id: "8",
    name: "Mr. Tunde Adebayo",
    email: "tunde.adebayo@son.gov.ng",
    avatar: "",
    role: "Document Controller",
    department: "Document Management",
    status: "Active" as const,
    joinedDate: "20 Apr 2021, 9:55 am",
    phone: "+234 808 901 2345",
    address: "SON Document Center, Ibadan, Nigeria",
    bio: "Ensures proper versioning, storage, and security of SON’s certification and compliance documents.",
  },
  {
    id: "9",
    name: "Mrs. Ruth Eze",
    email: "ruth.eze@son.gov.ng",
    avatar: "",
    role: "Quality Control Officer",
    department: "Testing and Calibration",
    status: "Active" as const,
    joinedDate: "11 Nov 2020, 1:00 pm",
    phone: "+234 809 012 3456",
    address: "SON Testing Laboratory, Port Harcourt, Nigeria",
    bio: "Conducts laboratory testing and calibration services for product quality verification.",
  },
  {
    id: "10",
    name: "Mr. Kelvin Udo",
    email: "kelvin.udo@son.gov.ng",
    avatar: "",
    role: "Audit Supervisor",
    department: "Internal Audit",
    status: "Active" as const,
    joinedDate: "17 Aug 2023, 5:45 pm",
    phone: "+234 810 123 4567",
    address: "SON Headquarters, Abuja, Nigeria",
    bio: "Leads internal audits to ensure compliance with regulatory, financial, and operational standards.",
  },
  {
    id: "11",
    name: "Mrs. Ngozi Adewale",
    email: "ngozi.adewale@son.gov.ng",
    avatar: "",
    role: "Legal Adviser",
    department: "Legal Services",
    status: "Active" as const,
    joinedDate: "08 Mar 2023, 6:45 am",
    phone: "+234 811 234 5678",
    address: "SON Legal Department, Lagos, Nigeria",
    bio: "Provides legal guidance on standardization policies, contracts, and enforcement actions.",
  },
  {
    id: "12",
    name: "Mr. Samuel Okon",
    email: "samuel.okon@son.gov.ng",
    avatar: "",
    role: "Senior Data Analyst",
    department: "Strategic Planning and Data",
    status: "Active" as const,
    joinedDate: "27 Aug 2024, 9:30 pm",
    phone: "+234 812 345 6789",
    address: "SON Data Unit, Abuja, Nigeria",
    bio: "Analyzes compliance and performance data to support national standardization strategies.",
  },
];
