import { Document } from "../types";

export const mockDocuments: Document[] = [
  {
    id: "1",
    title: "Technical Specifications",
    fileName: "tech_specs_v2.pdf",
    fileType: "application/pdf",
    fileSize: 2450,
    category: "Request Documents",
    relatedTo: "REQ-2024-001",
    uploadedBy: "Easy Gee",
    uploadedDate: "2024-01-25",
    version: 2,
    tags: ["technical", "specifications"],
    description: "Technical specifications for desktop computers",
  },
  {
    id: "2",
    title: "Purchase Order - Office Chairs",
    fileName: "PO-2024-002.pdf",
    fileType: "application/pdf",
    fileSize: 1200,
    category: "Purchase Orders",
    relatedTo: "PO-2024-002",
    uploadedBy: "John Procurement",
    uploadedDate: "2024-01-24",
    version: 1,
    tags: ["purchase-order", "furniture"],
    description: "Purchase order for office chairs",
  },
  {
    id: "3",
    title: "Invoice - TechHub Nigeria",
    fileName: "invoice_techhub_jan.pdf",
    fileType: "application/pdf",
    fileSize: 890,
    category: "Invoices",
    relatedTo: "PO-2024-001",
    uploadedBy: "Sarah Admin",
    uploadedDate: "2024-01-23",
    version: 1,
    tags: ["invoice", "payment"],
  },
  {
    id: "4",
    title: "Payment Receipt",
    fileName: "receipt_TRF-2024-001.pdf",
    fileType: "application/pdf",
    fileSize: 450,
    category: "Receipts",
    relatedTo: "TRF-2024-001",
    uploadedBy: "John Finance",
    uploadedDate: "2024-01-22",
    version: 1,
    tags: ["receipt", "payment"],
  },
  {
    id: "5",
    title: "Budget Proposal Q1",
    fileName: "budget_q1_2024.xlsx",
    fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    fileSize: 3200,
    category: "Budget Documents",
    uploadedBy: "Sarah Admin",
    uploadedDate: "2024-01-20",
    version: 3,
    tags: ["budget", "quarterly"],
    description: "Q1 2024 budget proposal and breakdown",
  },
];
